{{ if .Values.argocd.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: tools
  sources:
    - repoURL: https://github.com/sekthor/infrastructure.git
      path: argocd
      targetRevision: 5.51.6
      helm:
        releaseName: argocd
        {{ if .Values.argocd.valuesFiles }}
        valueFiles:
          {{- range $k, $v := .Values.argocd.valuesFiles }}
          - {{ $v }} 
          {{- end }}
        {{ end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  info:
    - name: 'documentation'
      value: 'https://argo-cd.readthedocs.io/en/stable/'
    - name: 'source code'
      value: 'https://github.com/argoproj/argo-cd'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
{{ end }}