apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toolstack
  namespace: argocd
spec:
  project: tools
  sources:
    - repoURL: https://github.com/sekthor/infrastructure.git
      path: toolstack
      targetRevision: HEAD
      helm:
        releaseName: toolstack
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false