apiVersion: v2
name: grafana
description: a parameterized grafana for toolstack
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: grafana
    version: 7.0.17
    repository: https://grafana.github.io/helm-charts
