apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: tools
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.51.6
      path: argocd
      chart: argo-cd
      helm:
        releaseName: argocd
        valueFiles:
        - $values/toolstack/apps/argocd-values.yaml
    - repoURL: https://github.com/sekthor/infrastructure.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  info:
    - name: 'Example:'
      value: 'https://example.com'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false