apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toolstack
  namespace: argocd
spec:
  project: tools
  sources:
    - repoURL: https://github.com/sekthor/infrastructure.git
      path: toolstack/clusters/lab
      targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false