apiVersion: v2
name: tempo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: tempo
    version: 1.7.1
    repository: https://grafana.github.io/helm-charts
